# Generated by Django 5.0.2 on 2024-02-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='workers/images/default.jpg', upload_to='workers/images/')),
                ('username', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('titles', models.TextField(blank=True, null=True)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
